# Generated by Django 5.1.4 on 2024-12-19 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_paragraph_ru', models.CharField(max_length=50)),
                ('first_paragraph_en', models.CharField(max_length=50)),
                ('second_paragraph_ru', models.CharField(max_length=50)),
                ('second_paragraph_en', models.CharField(max_length=50)),
                ('third_paragraph_ru', models.CharField(max_length=50)),
                ('third_paragraph_en', models.CharField(max_length=50)),
                ('fourth_paragraph_ru', models.CharField(max_length=50)),
                ('fourth_paragraph_en', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'About Us Card',
                'verbose_name_plural': 'About Us Card',
            },
        ),
        migrations.CreateModel(
            name='Parquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_ru', models.TextField()),
                ('description_en', models.TextField()),
                ('image_left', models.FileField(upload_to='Parquet/')),
                ('image_right', models.FileField(upload_to='Parquet/')),
            ],
            options={
                'verbose_name': 'Parquet',
                'verbose_name_plural': 'Parquet',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='Projects/')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_ru', models.TextField()),
                ('comment_en', models.TextField()),
                ('fullname', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='Reviews/')),
            ],
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_ru', models.TextField()),
                ('description_en', models.TextField()),
                ('image', models.FileField(upload_to='AboutUs/')),
                ('cards', models.ManyToManyField(blank=True, to='main.aboutuscard')),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_banner', models.FileField(upload_to='main_banner/')),
                ('about_us', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_page_about_us', to='main.aboutus')),
                ('local_restoration', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_page_restoration', to='main.parquet')),
                ('parquet_installation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_page_installation', to='main.parquet')),
                ('parquet_refinishing', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_page_refinishing', to='main.parquet')),
                ('parquet_sanding', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_page_sanding', to='main.parquet')),
                ('projects', models.ManyToManyField(blank=True, to='main.projects')),
                ('reviews', models.ManyToManyField(blank=True, to='main.reviews')),
            ],
        ),
    ]
