# Generated by Django 5.1.4 on 2024-12-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_aboutus_options_alter_homepage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parquet',
            name='title_en',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parquet',
            name='title_ru',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
