# Generated by Django 5.1.4 on 2024-12-19 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_parquet_title_en_parquet_title_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='cards',
        ),
    ]
