# Generated by Django 5.1.4 on 2025-01-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_aboutus_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='OurGallery/')),
            ],
            options={
                'verbose_name': 'Our Gallery Banner',
                'verbose_name_plural': 'Our Gallery Banner',
            },
        ),
        migrations.AddField(
            model_name='homepage',
            name='gallery',
            field=models.ManyToManyField(blank=True, to='main.ourgallery'),
        ),
    ]
